### ISSUE TITLE
Any plans to update to 3-0-stable?

### ISSUE THREAD

**Issue by ThomasBush** [Willianvdv/spree_algolia#1]
Just wanted to reach out to see if this project is still on your radar.  I forked but have not been able to figure out how to get this to work.  Specifically, I am able to index my products, but the Algolia searcher is not being used.

**Comment by Willianvdv** [comment]
I'm not working on a 3-0 shop and therefor don't have plans to upgrade this gem. If I would upgrade I think I'd remove the search logic from Spree (this gem adds a searcher class that powers ransack) and use Algolia's Instasearch.js (https://github.com/algolia/instant-search-demo) instead.

**Comment by ThomasBush** [comment]
Thanks for the advice @Willianvdv.  I have a lot of experience with instant search, but minimal with spree and searcher classes so I think that's the route I will take.  Thanks!
